### PR TITLE
deerma.humidifier.mjjsq device update

### PR DESCRIPTION
**Pull request by ftp27**
- Mute switch added
- Water level value to percents changed
- Humidity limits extended

### CODE REVIEW

**Comment by Aekung** [comment]
Hello,

What would be the best way to update with your branch? All these features are what I'm waiting for on the official release. 

Thank you and looking forward to hearing from you.

**Comment by russtone** [comment]
Thanks for the contribution!

**Comment by Aekung** [comment]
Updated,

Thanks for your super fast merging @russtone 
Also thanks for the contribution @ftp27  =)

**Comment by Aekung** [comment]
Not sure if the problem is related to this pull request but after the latest update of the plubin (version 1.3.0), Humidifier makes homebridge devices become unresponsive and require few attempts in order to re-load all accessories and make them become responsive again.

Currently, I have uninstalled the plugin and everything is back to normal. I'm using MJJSQ as my humidifier.

Not sure if you are experiencing the same. For some reason, I can't seem to reverse back to the previous version as well.

**Comment by ftp27** [comment]
In my case, it takes 5 or 7 seconds to make a device available after HomeKit app was launched. But I thought it's the device issue because I have the same timeouts in Xiaomi Home app.

**Pull request merged**
